### ISSUE TITLE
How do you get other animals?

### ISSUE THREAD

**Issue by aharris88** [johnnyt/cowsay#4]
I see in the repo that there are multiple animals besides the cow. How do you choose which animal you want?

**Comment by johnnyt** [comment]
There's no way right now to specify a character to use from the command line - it always uses a random one.

You can use a specific one using:

Shell:
```
ruby -rcowsay -e 'puts Cowsay::Character::Cheese.say "hello"'
```

Ruby:
```ruby
require 'cowsay'
puts Cowsay::Character::Cheese.say "hello"
```

**Comment by aharris88** [comment]
Oh, I see.
